<?php
$assignsDetails = [
    [
       'date' => '2024-11-07',
       'time' => '09:30 a.m.',
       'route' => '438',
       'from' => 'Kottawa',
       'to' => 'Colombo',
       'busNo' => 'XP-2341',
    ],
    [
        'date' => '2024-11-07',
        'time' => '11:00 a.m.',
        'route' => '138',
        'from' => 'Colombo',
        'to' => 'Kottawa',
        'busNo' => 'XP-2341',
    ],
    [
        'date' => '2024-11-07',
        'time' => '11:00 a.m.',
        'route' => '138',
        'from' => 'Galle',
        'to' => 'Kandy',
        'busNo' => 'XP-2397',
    ],
    [
        'date' => '2024-11-08',
        'time' => '11:00 a.m.',
        'route' => '440',
        'from' => 'Kandy',
        'to' => 'Galle',
        'busNo' => 'XP-2397',
    ],
    [
        'date' => '2024-11-09',
        'time' => '11:00 a.m.',
        'route' => '440',
        'from' => 'Galle',
        'to' => 'Kandy',
        'busNo' => 'XP-2397',
    ],
    [
        'date' => '2024-11-10',
        'time' => '11:00 a.m.',
        'route' => '440',
        'from' => 'Kandy',
        'to' => 'Galle',
        'busNo' => 'XP-2397',
    ],
    [
        'date' => '2024-11-15',
        'time' => '09:00 a.m.',
        'route' => '22',
        'from' => 'Kandy',
        'to' => 'Ampara',
        'busNo' => 'HG-9462',
    ],
    [
        'date' => '2024-11-16',
        'time' => '09:00 a.m.',
        'route' => '22',
        'from' => 'Ampara',
        'to' => 'Kandy',
        'busNo' => 'HG-9462',
    ],
    [
        'date' => '2024-11-17',
        'time' => '09:00 a.m.',
        'route' => '22',
        'from' => 'Kandy',
        'to' => 'Ampara',
        'busNo' => 'HG-9462',
    ],
    [
        'date' => '2024-11-18',
        'time' => '09:00 a.m.',
        'route' => '22',
        'from' => 'Ampara',
        'to' => 'Kandy',
        'busNo' => 'HG-9462',
    ],
    [
        'date' => '2024-11-19',
        'time' => '09:00 a.m.',
        'route' => '22',
        'from' => 'Kandy',
        'to' => 'Ampara',
        'busNo' => 'HG-9462',
    ],
    [
        'date' => '2024-11-20',
        'time' => '09:00 a.m.',
        'route' => '22',
        'from' => 'Ampara',
        'to' => 'Kandy',
        'busNo' => 'HG-9462',
    ],
    [
        'date' => '2024-11-21',
        'time' => '09:00 a.m.',
        'route' => '22',
        'from' => 'Kandy',
        'to' => 'Ampara',
        'busNo' => 'HG-9462',
    ],
    [
        'date' => '2024-11-22',
        'time' => '09:00 a.m.',
        'route' => '22',
        'from' => 'Ampara',
        'to' => 'Kandy',
        'busNo' => 'HG-9462',
    ],
    [
        'date' => '2024-12-01',
        'time' => '07:00 p.m.',
        'route' => '11',
        'from' => 'Matara',
        'to' => 'Ratnapura',
        'busNo' => 'PO-4698',
    ],
    [
        'date' => '2024-12-02',
        'time' => '07:00 p.m.',
        'route' => '11',
        'from' => 'Ratnapura',
        'to' => 'Matara',
        'busNo' => 'PO-4698',
    ],
    [
        'date' => '2024-12-03',
        'time' => '07:00 p.m.',
        'route' => '11',
        'from' => 'Matara',
        'to' => 'Ratnapura',
        'busNo' => 'PO-4698',
    ],
    [
        'date' => '2024-12-04',
        'time' => '07:00 p.m.',
        'route' => '11',
        'from' => 'Ratnapura',
        'to' => 'Matara',
        'busNo' => 'PO-4698',
    ],
    [
        'date' => '2024-12-05',
        'time' => '07:00 p.m.',
        'route' => '11',
        'from' => 'Matara',
        'to' => 'Ratnapura',
        'busNo' => 'PO-4698',
    ],
    [
        'date' => '2024-12-06',
        'time' => '07:00 p.m.',
        'route' => '11',
        'from' => 'Ratnapura',
        'to' => 'Matara',
        'busNo' => 'PO-4698',
    ],
    [
        'date' => '2024-12-07',
        'time' => '09:30 a.m.',
        'route' => '438',
        'from' => 'Kottawa',
        'to' => 'Colombo',
        'busNo' => 'XP-2341',
     ],
     [
         'date' => '2024-12-07',
         'time' => '11:00 a.m.',
         'route' => '138',
         'from' => 'Colombo',
         'to' => 'Kottawa',
         'busNo' => 'XP-2341',
     ],
     [
        'date' => '2024-12-08',
        'time' => '11:00 a.m.',
        'route' => '440',
        'from' => 'Kandy',
        'to' => 'Galle',
        'busNo' => 'XP-2397',
     ],
     [
        'date' => '2024-12-08',
        'time' => '11:00 a.m.',
        'route' => '440',
        'from' => 'Kandy',
        'to' => 'Galle',
        'busNo' => 'XP-2397',
     ],
     [
         'date' => '2024-12-08',
         'time' => '11:00 a.m.',
         'route' => '440',
         'from' => 'Kandy',
         'to' => 'Galle',
         'busNo' => 'XP-2397',
     ],
     [
         'date' => '2024-12-09',
         'time' => '11:00 a.m.',
         'route' => '440',
         'from' => 'Galle',
         'to' => 'Kandy',
         'busNo' => 'XP-2397',
     ],
     [
         'date' => '2024-12-10',
         'time' => '11:00 a.m.',
         'route' => '440',
         'from' => 'Kandy',
         'to' => 'Galle',
         'busNo' => 'XP-2397',
     ],
    
];

// Current date for comparison
$currentDate = date("Y-m-d");