<?php
$busDetails = [
    [
        'busId' => 'BUS101',
        'busNumber' => 'NA-1234',
        'routeNumber' => '101',
        'route' => 'Colombo - Ampara',
        'busType' => '1',
        'stops' => ['Colombo Fort', 'Pettah', 'Kandy', 'Mahiyanganaya', 'Ampara'],
        'start' => 'Colombo',
        'destination' => 'Ampara',
        'rating' => '4.4',
        'passengers' => '34',
        'price' => 'Rs. 700',
     
    ],
    [
        'busId' => '2',
        'busNumber' => 'NA-5678',
        'routeNumber' => '102',
        'route' => 'Colombo - Kandy',
        'busType' => '2',
        'stops' => ['Colombo Fort', 'Pettah', 'Kadawatha', 'Peradeniya', 'Kandy'],
        'start' => 'Colombo',
        'destination' => 'Kandy',
        'rating' => '4.7',
        'passengers' => '20',
        'price' => 'Rs. 1200',
    
    ],
    [
        'busId' => '3',
        'busNumber' => 'NA-9012',
        'routeNumber' => '103',
        'route' => 'Colombo - Galle',
        'busType' => '1',
        'stops' => ['Colombo Fort', 'Pettah', 'Panadura', 'Kalutara', 'Galle'],
        'start' => 'Colombo',
        'destination' => 'Galle',
        'rating' => '4.2',
        'passengers' => '40',
        'price' => 'Rs. 800',
     
    ],
    [
        'busId' => '4',
        'busNumber' => 'NA-3456',
        'routeNumber' => '104',
        'route' => 'Colombo - Jaffna',
        'busType' => '2',
        'stops' => ['Colombo Fort', 'Kurunegala', 'Anuradhapura', 'Vavuniya', 'Jaffna'],
        'start' => 'Colombo',
        'destination' => 'Jaffna',
        'rating' => '4.6',
        'passengers' => '25',
        'price' => 'Rs. 1500',
      
    ],
    [
        'busId' => '5',
        'busNumber' => 'NA-7890',
        'routeNumber' => '105',
        'route' => 'Colombo - Negombo',
        'busType' => '1',
        'stops' => ['Colombo Fort', 'Peliyagoda', 'Katunayake', 'Negombo'],
        'start' => 'Colombo',
        'destination' => 'Negombo',
        'rating' => '4.0',
        'passengers' => '50',
        'price' => 'Rs. 300',
     
    ],
    [
        'busId' => '6',
        'busNumber' => 'NA-6543',
        'routeNumber' => '106',
        'route' => 'Colombo - Matara',
        'busType' => '2',
        'stops' => ['Colombo Fort', 'Kalutara', 'Galle', 'Weligama', 'Matara'],
        'start' => 'Colombo',
        'destination' => 'Matara',
        'rating' => '4.8',
        'passengers' => '18',
        'price' => 'Rs. 1000',
     
    ],
    [
        'busId' => '7',
        'busNumber' => 'NA-5543',
        'routeNumber' => '106',
        'route' => 'Colombo - Matara',
        'busType' => '1',
        'stops' => ['Colombo Fort', 'Kalutara', 'Galle', 'Weligama', 'Matara'],
        'start' => 'Colombo',
        'destination' => 'Matara',
        'rating' => '4.8',
        'passengers' => '18',
        'price' => 'Rs. 1000',
     
    ]
];
?>