<?php
$busDetails = [
    [
        'busId' => '1',
        'busNumber' => 'NA-1234',
        'routeNumber' => '101',
        'route' => 'Colombo - Ampara',
        'busType' => '38 Seats',
        'departure' => '6:00AM',
        'arrival' => '3:00PM',
        'duration' => '9 hours 30 mins',
        'stops' => ['Colombo Fort', 'Kandy', 'Ampara'],
        'rating' => '4.4',
        'passengers' => '34',
        'price' => 'Rs. 700',
        'cheapest' => true
    ],
    [
        'busId' => '2',
        'busNumber' => 'NA-5678',
        'routeNumber' => '102',
        'route' => 'Colombo - Kandy',
        'busType' => '38 Seats',
        'departure' => '8:00AM',
        'arrival' => '11:30AM',
        'duration' => '3 hours 30 mins',
        'stops' => ['Colombo Fort', 'Peradeniya', 'Kandy'],
        'rating' => '4.7',
        'passengers' => '20',
        'price' => 'Rs. 1200',
        'cheapest' => false
    ],
    [
        'busId' => '3',
        'busNumber' => 'NA-9012',
        'routeNumber' => '103',
        'route' => 'Colombo - Galle',
        'busType' => '38 Seats',
        'departure' => '9:00AM',
        'arrival' => '1:00PM',
        'duration' => '4 hours',
        'stops' => ['Colombo Fort', 'Kalutara', 'Galle'],
        'rating' => '4.2',
        'passengers' => '40',
        'price' => 'Rs. 800',
        'cheapest' => false
    ],
    [
        'busId' => '4',
        'busNumber' => 'NA-3456',
        'routeNumber' => '104',
        'route' => 'Colombo - Jaffna',
        'busType' => '38 Seats',
        'departure' => '10:00AM',
        'arrival' => '5:00PM',
        'duration' => '7 hours',
        'stops' => ['Colombo Fort', 'Vavuniya', 'Jaffna'],
        'rating' => '4.6',
        'passengers' => '25',
        'price' => 'Rs. 1500',
        'cheapest' => true
    ],
    [
        'busId' => '5',
        'busNumber' => 'NA-7890',
        'routeNumber' => '105',
        'route' => 'Colombo - Negombo',
        'busType' => '38 Seats',
        'departure' => '11:00AM',
        'arrival' => '12:00PM',
        'duration' => '1 hour',
        'stops' => ['Colombo Fort', 'Negombo'],
        'rating' => '4.0',
        'passengers' => '50',
        'price' => 'Rs. 300',
        'cheapest' => true
    ],
    [
        'busId' => '6',
        'busNumber' => 'NA-6543',
        'routeNumber' => '106',
        'route' => 'Colombo - Matara',
        'busType' => '38 Seats',
        'departure' => '2:00PM',
        'arrival' => '7:00PM',
        'duration' => '5 hours',
        'stops' => ['Colombo Fort', 'Ratnapura', 'Matara'],
        'rating' => '4.8',
        'passengers' => '18',
        'price' => 'Rs. 1000',
        'cheapest' => false
    ]
];
?>
